apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwameistor-scheduler
  namespace: {{ .Release.Namespace}}
spec:
  replicas: {{ .Values.hwameistorSchedulerReplicas}}
  selector:
    matchLabels:
      app: hwameistor-scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hwameistor-scheduler
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: Exists
      containers:
      - command:
        - kube-scheduler
        - -v=2
        - --bind-address=0.0.0.0
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --scheduler-name=hwameistor-scheduler
        - --leader-elect=false
        - --leader-elect-resource-name=hwameistor-scheduler
        - --leader-elect-resource-namespace={{ .Release.Namespace}}
        - --config=/etc/hwameistor/hwameistor-scheduler-config.yaml
        image: {{ .Values.hwameistorSchedulerImage}}
        imagePullPolicy: IfNotPresent
        name: hwameistor-kube-scheduler
        resources:
          limits:
            cpu: {{ .Values.hwameistorSchedulerResources.limits.cpu}}
            memory: {{ .Values.hwameistorSchedulerResources.limits.memory}}
          requests:
            cpu: {{ .Values.hwameistorSchedulerResources.requests.cpu}}
            memory: {{ .Values.hwameistorSchedulerResources.requests.memory}}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /etc/hwameistor/
          name: hwameistor-scheduler-config
          readOnly: true
      volumes:
      - hostPath:
          path: {{ .Values.schedulerKubeApiServerConfigFilePath}}
          type: FileOrCreate
        name: kubeconfig
      - configMap:
          name: hwameistor-scheduler-config 
          items:
          - key: hwameistor-scheduler-config.yaml
            path: hwameistor-scheduler-config.yaml
        name: hwameistor-scheduler-config
      serviceAccountName: hwameistor-admin 
      serviceAccount: hwameistor-admin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        operator: Exists
